### PR TITLE
Feature/dynamic list of contributors

### PR DESCRIPTION
**Pull request by adrianoluisalmeida**
## Proposed Changes
Implementation of dynamic list of collaborators
screencapture-localhost-3000-docs-project-acknowledgements-2021-11-07-16_36_07

### CODE REVIEW

**Review by jhomarolo — APPROVED** [review]

**Comment by jhomarolo** [comment]
@adrianoluisalmeida the build is breaking: "Invalid: lock file's node-fetch@2.6.1 does not satisfy node-fetch@^3.0.0"

**Comment by adrianoluisalmeida** [comment]
Hi @jhomarolo !!! I had not sent the file package.lock. 
Now i sent!

**Comment by jhomarolo** [comment]
@adrianoluisalmeida the build is broken now: https://github.com/herbsjs/herbsjs.github.io/runs/4147022313?check_suite_focus=true

**Comment by adrianoluisalmeida** [comment]
@jhomarolo 
I am sad :(  Now i installed the dot/env to run from the command line. 

Will it work now?

**Pull request merged**
