### PR TITLE
added community contents

### PR DESCRIPTION
**Pull request by italojs**
Fixes https://github.com/herbsjs/herbsjs.github.io/issues/109

## Proposed Changes

Created a page for linking the content created by the community

Screen Shot 2022-11-26 at 08 21 16

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

### CODE REVIEW

**Comment by italojs** [comment]
@dalssoft @jhomarolo

**Comment by jhomarolo** [comment]
Make sense all contents labels be in English ?

**Comment by italojs** [comment]
i dont think so, because it could be a bad experience when the developer access this page, open a article and it be in another language.

what we could to do is add a language info. example:

language: en
language: pt-br

**Comment by dalssoft** [comment]
Great PR. Thank you @italojs 

Regarding the content, I agree with @jhomarolo . I think the content of the site should be all English. If the link takes to a non-engligh content, it should be indicated, as you suggested.

**Comment by jhomarolo** [comment]
Can you please send a print screen about the new version?

**Comment by italojs** [comment]
Screen Shot 2023-01-27 at 14 40 52

**Review by dalssoft — APPROVED** [review]

**Comment by dalssoft** [comment]
@italojs, PR approved. But we changed the policy to only accept signed commits. Could you singed it?

> The base branch requires all commits to be signed

**Comment by italojs** [comment]
Screenshot 2023-03-10 at 13 40 40
 done

**Comment by jhomarolo** [comment]
@italojs  I think the link is not working.

https://herbsjs.org/docs/project/communitycontent when I click in some news, nothing happens!

**Pull request merged**
